name: Cypress Tests
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: cypress install
        uses: cypress-io/github-action@v2
        with:
          headless: true
          spec: cypress/integration/api/*
